name: 04-Artifact-Demo

on:
  workflow_dispatch:

jobs:
  build-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create artifact file
        run: |
          echo "This is an artifact generated in the build job." > artifact.txt
          echo "Created on $(date)" >> artifact.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: artifact.txt

  download-artifact:
    runs-on: ubuntu-latest
    needs: build-artifact
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact

      - name: Show artifact content
        run: cat artifact.txt
