name: Call Reusable Workflow Demo

on:
  workflow_dispatch:

jobs:
  use-reusable:
    uses: ./.github/workflows/artifact-demo.yml
    with:
      build-message: "Hello from caller workflow artifact demo!"

  consume-artifact:
    runs-on: ubuntu-latest
    needs: use-reusable
    steps:
      - name: Download reusable artifact
        uses: actions/download-artifact@v4
        with:
          name: reusable-artifact

      - name: Show artifact content
        run: cat reusable-artifact.txt
